### PR TITLE
feat: retry #900

### PR DESCRIPTION
**Pull request by louis030195**
disclaimer: did not test this, if anyone will to do

### CODE REVIEW

**Comment by FabianLars** [comment]
Thanks! Could you also add a change file and run `pnpm build` once (we need to commit the dist files)

**Comment by louis030195** [comment]
@FabianLars good now?

keep wasting my time on these issue https://github.com/mediar-ai/screenpipe/actions/runs/12244105301/job/34155163076

**Comment by FabianLars** [comment]
One thing i forgot last time (sorry), i think we should default to no retries. People are using this action in private repos and i don't want to x3 their bills.

**Comment by louis030195** [comment]
@FabianLars done

**Comment by FabianLars** [comment]
Thanks! I'll merge this tomorrow morning.

**Comment by FabianLars** [comment]
i'm so close to rewriting the action in rust 🤣

**Comment by FabianLars** [comment]
please don't tell anyone i wasted _hours_ on an `attemps` vs `attempts` typo 😂

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
