### PR TITLE
fix: support non zipped updater

### PR DESCRIPTION
**Pull request by Legend-Master**
Reference: https://github.com/tauri-apps/plugins-workspace/pull/1174

### CODE REVIEW

**Comment by Legend-Master** [comment]
Waiting on https://github.com/tauri-apps/tauri/pull/9446

**Comment by FabianLars** [comment]
we'll need a good old changefile :)

**Comment by Legend-Master** [comment]
I can't test this easily and I think the old action can't handle multiple signatures generated by the new cli, so we might need to 
hurry up

**Comment by alunogabrielgava123** [comment]
corrto

**Comment by Legend-Master** [comment]
Waiting on https://github.com/tauri-apps/tauri/pull/9883 (need to also update v2 CI's config files)

**Review by FabianLars — APPROVED** [review]

**Pull request merged**
