### PR TITLE
fix: unexpected return in uploadAssets

### PR DESCRIPTION
**Pull request by chiichen**

### CODE REVIEW

**Comment by chiichen** [comment]
Fix #975  @FabianLars Can you give it a brief review? It's quite simple and I do believe it can fix it. I added a return(https://github.com/tauri-apps/tauri-action/pull/895/files#diff-eab77d5479dfaa2e1e42c5a470ba2543fd78189b8a71e9de66c2f0b1ba74cb2fL61) by mistake (sadly, it's been a long time since I drafted the PR. I can hardly remember the motivation for making such a change.)

**Comment by chiichen** [comment]
https://github.com/tauri-apps/tauri-action/issues/975#issuecomment-2539268074 It's been tested

**Comment by FabianLars** [comment]
I'll merge it in a few hours when I'm back in the hotel. I have to say, I noticed the `return` change in the initial PR but thought it was actually not doing anything (basically being useless). I still don't see how it could cause this issue but I can't read code on mobile properly so...

**Comment by FabianLars** [comment]
Actually no, I'll merge it now and see if CI is happy then (it'll upload the assets for branches in this repo)

**Comment by FabianLars** [comment]
Thank you for the quick fix!

**Comment by chiichen** [comment]
> I'll merge it in a few hours when I'm back in the hotel. I have to say, I noticed the `return` change in the initial PR but thought it was actually not doing anything (basically being useless). I still don't see how it could cause this issue but I can't read code on mobile properly so...

the return line is in the for loop so it breaks the loop. that's why we skip the other artifacts

**Comment by FabianLars** [comment]
Ah damn, I'm blind 🤣

**Comment by chiichen** [comment]
@FabianLars Can you release a patch version for it? https://github.com/tauri-apps/tauri-action/pull/979

**Comment by FabianLars** [comment]
i'm back tomorrow, will do it then.

**Pull request merged**
