### PR TITLE
feat: Add `appVersion` output

### PR DESCRIPTION
**Pull request by A-kirami**
### Description
This pull request aims to enhance the utility of our GitHub Action by introducing a new output variable: `appVersion`. This addition serves the purpose of conveniently providing the version of the application being processed. The inclusion of this output variable will enable downstream workflows to easily access and utilize the current application version.

### Changes Made
- Added a new output variable `appVersion` to the existing list of outputs.
  - `appVersion`: The version of the application.

### Context
The `appVersion` output is crucial for downstream workflows that depend on knowing the version of the application. This information can be utilized in various scenarios, such as deployment processes or other automated tasks.

### Example Usage
```yaml
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Tauri Action
      id: tauri-action
      uses: tauri-apps/tauri-action@v0
      with:
        # Other input parameters
        ...

    - name: Use 'appVersion' in Subsequent Steps
      run: |
        echo "Application Version: ${{ steps.tauri-action.outputs.appVersion }}"
      # Continue with other steps as needed
```

### CODE REVIEW

**Comment by FabianLars** [comment]
Nice addition, thanks! Could you run `pnpm install && pnpm build` and commit the new dist files too please? Oh and a changefile like this one too https://github.com/tauri-apps/tauri-action/blob/dev/.changes/fix-member-globs.md

**Comment by A-kirami** [comment]
All set! Updated dist files and added the changefile. 😊

**Review by FabianLars — APPROVED** [review]
Thanks :)

**Comment by FabianLars** [comment]
(i really need to update the real world tests so they don't just fail on external prs 😅)

**Comment by moranbw** [comment]
I don't see this as available yet.  Do I need to update my action somehow?  VS Code plugin does not recognize `appVersion` output, but it does recognize the others like `releaseId`.   I tried anyway, and it just showed up as blank in the subsequent step I tried to use it.

**Comment by FabianLars** [comment]
Will be available once i merge https://github.com/tauri-apps/tauri-action/pull/610. Should happen next week. If you need it urgently you can use the action from git directly via `uses: tauri-apps/tauri-action@dev`

**Pull request merged**
