### PR TITLE
fix: tauri 2.0.0-beta publish failure

### LINKED ISSUE #701: productName compatibility with Tauri 2 beta
Forgive me if any of my terminology is off, I'm pretty new to rust...

In Tauri 2.x, the config file appears to have changed. For this issue, the notable change is that `productName` is now a top-level item instead of being nested underneath `package`.

This results in the following error when the action tries to locate the artifacts if a `productName` is set in `tauri.conf.json`. Note that the action is looking for a file named `tortoise-native*` when it should be looking for `The Tortoise*`

In this case, my crate is named `tortoise-native` and my `productName` is `The Tortoise`.
```
...
    Finished 2 bundles at:
        /Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/The Tortoise.app
        /Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/dmg/The Tortoise_0.7.0_universal.dmg
Looking for artifacts in:
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/dmg/tortoise-native_0.7.0_universal.dmg
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/tortoise-native.app
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/tortoise-native.app.tar.gz
/Users/<USERNAME>/code/actions-runner/_work/tortoise-native/tortoise-native/src-tauri/target/universal-apple-darwin/release/bundle/macos/tortoise-native.app.tar.gz.sig
```

This seems to be the code of interest:
https://github.com/tauri-apps/tauri-action/blob/4bb1df96ee90cc64b4315bfaf82f4fe70d9d521e/src/utils.ts#L281-L289

I'm not sure what your plans are for 2.x support, but one easy way to address this particular issue would be to add  an additional `if` to cover this case. Specifically, check the top level of `config` for `productName` (and likely other variables as well).

I'm happy to make a PR, but wanted to check before I went ahead with anything.

### PR DESCRIPTION
**Pull request by l1xnan**
tauri 2.0.0-beta `TauriConfig` structure has changed

fixes #701

### CODE REVIEW

**Comment by FabianLars** [comment]
Hi, thanks for contributing! A few things before we can merge this:
1) We normally require all commits to be [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits), but it's not enforced in this repo yet so don't sweat over it if it's too much trouble.
2) This is not the only thing that changed in the config, i think it makes sense to have 2 config interfaces, one for each version, but i did not look into it too much yet. If you think this point is too much for you, I can work on this myself, it was on my todo anyway :)
3) please run `pnpm build` and commit the dist js files. without it your changes won't be applied
4) lastly, add a changefile similar to https://github.com/tauri-apps/tauri-action/blob/dev/.changes/fix-member-globs.md

Thank you :)

**Comment by l1xnan** [comment]
I'm sorry, I didn't think about it that much, it's just a temporary fix for the action default configuration (no `Project Initialisation` parameter passed in). 

The full modification does have more points to change, requiring new test cases to be added, documentation to be changed, and a new major version to be released (unlike `v0`), which is best handled in a new branch. I will try to fix it, but it may be slow, not sure how long it will take to finish it. If it's a higher priority in your TODO, that would be best!

**Comment by FabianLars** [comment]
yeah, don't worry about it. I'll do it today. Thanks for the work so far :)

**Comment by FabianLars** [comment]
Hi, the change ended up bigger than i hoped and i started on the upstream branch by accident so i opened a new PR. I added you as a co author though. Apologies and thanks again for contributing!

**Pull request closed without merging**
