### PR TITLE
fix: Change msi naming scheme for recent Tauri upgrades

### PR DESCRIPTION
**Pull request by jdukewich**
This action does not work with Windows bundles on the latest version of Tauri (see #225). I'm not sure when, but Tauri bundling changed the naming scheme of the output .msi installer.

[This file](https://github.com/tauri-apps/tauri/blob/dev/tooling/bundler/src/bundle/windows/msi/wix.rs#L194) in Tauri determines the outpath path name, and you can see it adds in the Wix Language.

Wix Language defaults to "en-US" as seen [here](https://github.com/tauri-apps/tauri/blob/dev/core/tauri-utils/src/config.rs#L149).

Docs showing the config path for Wix Language are [here](https://tauri.studio/docs/api/config#tauri.bundle.windows.wix.language).

If you want to test the action, test with `jdukewich/tauri-action@fix-windows-bundling`.

### CODE REVIEW

**Review by FabianLars — CHANGES_REQUESTED** [review]
Hey! Thanks so much for taking a stab at this ❤️ 
Unfortunately this is not quite correct as it isn't as easy as it seems at first glance.
wix.language isn't necessarily a string. It can be an array or an object too: https://tauri.studio/docs/distribution/windows.
The bundler will create one MSI for each language.

Personally i'd prefer to get it correct&complete before merging it. But i guess i'd also agree to merging this and add support for array/object later, just so it's working for the more common configs.
cc @lucasfernog

**Comment by jdukewich** [comment]
I can look more into that and work in support for all types of Wix Language. I wasn't too familiar with the full scope of config values originally. Is the general idea of the fix good as long as the types are correct and it supports multiple .msi for each language?

**Comment by FabianLars** [comment]
Yeah i think the idea is fine.
You just need to be careful with the updater zip&sig as these are only generated _once_ (for the first language specified). I mentioned that in our team chat because something about it feels weird (one zip is fine as it would just be too complicated otherwise, but still, _something_ feels off 😅)

**Comment by jdukewich** [comment]
Okay sounds good. And thanks for clarifying! Tauri is a large (but great!) project so it's tough to know all the specifics.

**Comment by FabianLars** [comment]
Yeah i'm with you there. Started with tauri pre-beta and joined the team half a year ago and i still don't know everything :D (especially after the huge audit changes lol)

**Comment by lucasfernog** [comment]
You're so close :) thanks for investigating this, I wanted to PR it but I didn't have the change yet. Now you just need to make it handle `language: string | string[] | { [language: string]: unknown }`

**Comment by jdukewich** [comment]
Any guidance on how the zip & sigs are generated? When I run builds locally I am only getting the .msi. I've also followed https://tauri.studio/docs/distribution/sign-windows/.

**Comment by FabianLars** [comment]
You need to enable the updater to get them, which is kinda annoying here because we force you to create singer keys for it.

**Comment by jdukewich** [comment]
I was able to test out my latest changes, they seemed to work with configs that look like
```
"wix": {         
  "language": "en-US"
}
```
or
```
"wix": {         
  "language": ["en-US", "pt-BR"]
}
```
or
```
"wix": {         
  "language": {
    "en-US": {
      "localePath": null
    },
    "pt-BR": {
      "localePath": null
    }
  }
}
```

Also, because of the `paths.filter(p => existsSync(p))` in core/index.ts, I don't think we need to worry about which language was "first" and gets the sig and zip.

**Comment by FabianLars** [comment]
> Also, because of the paths.filter(p => existsSync(p)) in core/index.ts, I don't think we need to worry about which language was "first" and gets the sig and zip.

Ah true, forgot about that.

LGTM, thanks again!

**Review by FabianLars — APPROVED** [review]

**Comment by FabianLars** [comment]
Can you add a changefile like this one <https://github.com/tauri-apps/tauri-action/blob/dev/.changes/workspace-support.md>, as it breaks support with the beta versions?
I think `patch` is fine as it's more of a fix than a feature even if it's breaking. We can still change that later but i want to get this PR merged.

Thanks 🙏

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
