### PR TITLE
Add updater artifacts when available

### PR DESCRIPTION
**Pull request by lemarier**
Part of #108

### CODE REVIEW

**Comment by lemarier** [comment]
Still failing
https://github.com/tauri-apps/tauri-action/actions/runs/829491498

Seems to be at github actions release level

**Comment by lemarier** [comment]
https://github.com/tauri-apps/tauri-action/blob/0eb61ed08a555e88ed78f693e9117ac75feb1653/packages/action/src/index.ts#L95

**Comment by lucasfernog** [comment]
Seems like we need to escape the space.

**Comment by lemarier** [comment]
> Seems like we need to escape the space.

What you think if we remove this;

```
 if (artifact.endsWith('.app')) {
    await execCommand(`tar czf "${artifact}.tgz" "${artifact}"`, {
        cwd: undefined
    })
    artifacts[i] += '.tgz'
}
```

The bundler (when updater is enabled) already generates `App.tar.gz` because he needs to sign the final `tar.gz` so we can't do it inside the action.

Maybe later we can add the bundler to generate the tar.gz if the updater isn't enabled if we saw a need.

**Comment by lucasfernog** [comment]
Issue fixed on #132

**Review by lucasfernog — APPROVED** [review]

**Pull request merged**
