### PR TITLE
Custom app name

### PR DESCRIPTION
**Pull request by Ludea**
Customize binary name

### CODE REVIEW

**Comment by FabianLars** [comment]
I don't think this approach will work. This will only tell the action where it should look for the app files, without renaming them. Therefore it should always fail to find the files 🤔 

p.s. sorry for the delay!

**Comment by Ludea** [comment]
The binaries are built with `tauri build ` ?
If yes, we have to modify tauri directly ?

**Comment by FabianLars** [comment]
> The binaries are built with tauri build ?

Yes.

> If yes, we have to modify tauri directly ?

Hmm, tricky. If you only want to rename the app bundles (like the .msi, .appimage, etc) then no. if you also want to change the name of the exe/binary inside that bundle than _maybe_, or i guess that's what the `productName` config is for. Either way i don't see us changing Tauri for this feature so let's keep it specific to the action.

**Comment by Ludea** [comment]
I see https://github.com/tauri-apps/tauri-action/pull/355. 
I don't read the PR yet, but it's a complete rewrite and reading https://github.com/tauri-apps/tauri-action/issues/354, it does the job of my PR.
Will wait the review of rewriting PR and close my PR if it resolve issue

**Comment by ngalaiko** [comment]
maybe a better approach to this is to take an additional param by the action of a config file that will be merged into the default config json? it will map directly to the `tauri build --config <config to merge>` and allow to be more flexible in defining pipelines (including binary name update)

**Comment by FabianLars** [comment]
@ngalaiko's idea works on the dev branch for some time already. Imho that's good enough. With my concerns voiced above i'll close this PR for now. Thank you :)

**Pull request closed without merging**
