### PR TITLE
fix: updater file name with spaces and v2 sig files

### LINKED ISSUE #843: latest.json file is not generated if productName contains spaces
Steps to reproduce:
1. Specify `"productName": "With spaces"` in `tauri.conf.json`
2. Run github action
3. `latest.json` is not uploaded, warning is printed into the log: `Asset not found for the updater JSON. Skipping upload...`

This seems to be a regression in a recent PR #766. In scope of it, a new approach has been introduced to detect zip file based on a signature file name: https://github.com/tauri-apps/tauri-action/pull/766/files#diff-aa2bda70857754a372eebc7152d28dbd36dba171538840d29aa7cbfa024ace09R131
However, when generating a basename normalization is not applied (spaces and other special symbols are not replaced with dots). Bacause of this, asset is not found and warning is printed.

### PR DESCRIPTION
**Pull request by Legend-Master**
Fixes #843

### CODE REVIEW

**Comment by Legend-Master** [comment]
I don't know how I gonna test this to be honest 😖

**Comment by FabianLars** [comment]
we can merge this (after ci is happy) and see how the ci run on the dev branch behaves. Or if you enable ci in your fork it should also upload everything to a draft release there.

**Comment by FabianLars** [comment]
Or maybe not quite. Just noticed that it skips the upload on the dev branch...

**Comment by Legend-Master** [comment]
I'll try to run it in my fork, at the mean time, do you know what is our updater public key? Seems like there's private key set in the actions, but no public key's found

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri-action/blob/dev/.github/fixtures/example-with-tauri-v1/src-tauri/tauri.conf.json#L41

**Comment by Legend-Master** [comment]
Hmm, still doesn't work yet

image

> https://github.com/Legend-Master/tauri-action-test/actions/runs/9757232213/job/26929173063

**Comment by FabianLars** [comment]
Ah that looks like my mistake, try adding this: https://github.com/tauri-apps/tauri-action/commit/f8044a1d9fa468d71dd285d9f17b467dc8c9b334#diff-eab77d5479dfaa2e1e42c5a470ba2543fd78189b8a71e9de66c2f0b1ba74cb2fR46

`<space>(` will get converted to `.` by github but our logic converts it to `..`

**Comment by Legend-Master** [comment]
Looking at https://github.com/Legend-Master/tauri-action-test/releases/tag/3 signature files seem missing, not sure if it's related to `.`/`..` to be honest

**Comment by FabianLars** [comment]
Yeah, the looking for artifcats log is also wrong, only checking for v1 sigs

**Comment by Legend-Master** [comment]
Trying it on https://github.com/Legend-Master/tauri-action-test/actions/runs/9757784582, upload sig files seem to work now, but not getting the asset for updater json

**Comment by Legend-Master** [comment]
should be good to go now

https://github.com/Legend-Master/tauri-action-test/actions/runs/9758129429
https://github.com/Legend-Master/tauri-action-test/releases/tag/7

**Pull request merged**
