### PR TITLE
feat: Support `--target` input in `args`

### LINKED ISSUE #176: aarch64 support?
Hello, is it possible to also add an aarch64 build with the releases?

### LINKED ISSUE #243: Handle universal and aarch64 targets
I can currently build for aarch64 targets by using a self-hosted action runner on an apple silicone mac.
The problem is that all the paths aren't automatically recognized:
```
2022-03-17T18:01:22.2682550Z    Finished 2 bundles at:
2022-03-17T18:01:22.2683610Z         /Users/user/actions-runner/_work/project/project/target/release/bundle/macos/Project.app
2022-03-17T18:01:22.2700850Z         /Users/user/actions-runner/_work/project/project/target/release/bundle/dmg/Project_0.1.21_aarch64.dmg
2022-03-17T18:01:22.2701870Z [vite-plugin-tauri]  Tauri build finished.
2022-03-17T18:01:22.3124470Z Expected artifacts paths:
2022-03-17T18:01:22.3225410Z /Users/user/actions-runner/_work/project/project/target/release/bundle/dmg/Project_0.1.21_x64.dmg
2022-03-17T18:01:22.3248440Z /Users/user/actions-runner/_work/project/project/target/release/bundle/macos/Project.app
2022-03-17T18:01:22.3255780Z /Users/user/actions-runner/_work/project/project/target/release/bundle/macos/Project.app.tar.gz
2022-03-17T18:01:22.3258900Z /Users/user/actions-runner/_work/project/project/target/release/bundle/macos/Project.app.tar.gz.sig
2022-03-17T18:01:22.3260130Z Artifacts: /Users/user/actions-runner/_work/project/project/target/release/bundle/macos/Project.app.
2022-03-17T18:01:22.6631630Z Found release with tag 0.1.21.
2022-03-17T18:01:22.6632090Z 
2022-03-17T18:01:22.6665300Z 
2022-03-17T18:01:22.6669470Z 
2022-03-17T18:01:22.6671720Z running tar [
2022-03-17T18:01:22.6672460Z   'czf',
2022-03-17T18:01:22.6673430Z   '/Users/user/actions-runner/_work/project/project/target/release/bundle/macos/Project.app.tar.gz',
2022-03-17T18:01:22.6674240Z   '-C',
2022-03-17T18:01:22.6675050Z   '/Users/user/actions-runner/_work/project/project/target/release/bundle/macos',
2022-03-17T18:01:22.6675810Z   'Project.app'
2022-03-17T18:01:22.6676340Z ]
```

In this case only `Project.app` is recognized but `Project_0.1.21_aarch64.dmg ` is ignored because `aarch64` doesn't match `process.arch`
used in the code here:
https://github.com/tauri-apps/tauri-action/blob/9816b49a0578c5711c6e0c340fedd192414fd8d8/packages/core/index.ts#L248

Similarly I can build universal apps:
```
     with:
        args: -- --target universal-apple-darwin
```
But the problem here is that tauri-action doesn't recognize any of the artifacts because they don't match the expected path names

```
2022-03-17T20:20:45.3165570Z  Finished 2 bundles at:
2022-03-17T20:20:45.3167070Z         /Users/user/actions-runner/_work/myproject/myproject/target/universal-apple-darwin/release/bundle/macos/Project.app
2022-03-17T20:20:45.3168430Z         /Users/user/actions-runner/_work/myproject/myproject/target/universal-apple-darwin/release/bundle/dmg/Project_0.1.21_universal.dmg
2022-03-17T20:20:45.3189960Z [vite-plugin-tauri]  Tauri build finished.
2022-03-17T20:20:45.3616230Z Expected artifacts paths:
2022-03-17T20:20:45.3617800Z /Users/user/actions-runner/_work/myproject/myproject/target/release/bundle/dmg/Project_0.1.21_x64.dmg
2022-03-17T20:20:45.3619020Z /Users/user/actions-runner/_work/myproject/myproject/target/release/bundle/macos/Project.app
2022-03-17T20:20:45.3620360Z /Users/user/actions-runner/_work/myproject/myproject/target/release/bundle/macos/Project.app.tar.gz
2022-03-17T20:20:45.3621590Z /Users/user/actions-runner/_work/myproject/myproject/target/release/bundle/macos/Project.app.tar.gz.sig
2022-03-17T20:20:45.3657480Z [error]No artifacts were found.
```

specifically `/target/universal-apple-darwin/release/bundle/macos/` doesn't match `/target/release/bundle/macos/`

Possible solutions:
 - add an environment variable/parameter for arch and then fall back on `process.arch` if not defined and add `universal-apple-darwin`, `x86_64-apple-darwin`, `aarch64-apple-darwin` as a possible path to look for artifacts.
 - add environment variables/parameters for the full path of each of the artifacts

### LINKED ISSUE #252: ability to specify a target
```yaml
      - name: install app dependencies and build it
        run: yarn && yarn build
      - uses: tauri-apps/tauri-action@dev
        with:
          tauriScript: yarn tauri build --target ${{ matrix.target }}
```
produces this
```rust

Run tauri-apps/tauri-action@dev
running yarn [ 'tauri', 'build', '--target', 'i686-pc-windows-msvc', 'build' ]
error: Found argument 'build' which wasn't expected, or isn't valid in this context
```
this feature is needed for building for 32 windows (surprisingly large user base)

### PR DESCRIPTION
**Pull request by FabianLars**
This is really not a nice solution, but a better one would need a bigger rewrite which i don't have time for tbh. We should have a `cargo metadata` follow-up PR either way in case people commit their config.toml file.

Another problem is how it deletes existing release assets. The way it is now it will remove them per OS, not per arch, so you can't upload a .dmg file for example for both arches. The `.app` file obviously has a naming problem, so maybe we don't want to support this at all right now?

~~Successful run: https://github.com/FabianLars/mw-toolbox/actions/runs/3078695681~~
Now with macos asset renaming per arch and better asset overwrite handling: https://github.com/FabianLars/mw-toolbox/actions/runs/3333153297 - i wonder how happy github was with me uploading over 30 release assets 🤔 

~~Release: https://user-images.githubusercontent.com/30730186/191006883-9a3e9887-e240-4067-8bf8-6733dbaf3c6a.png~~

New release: 
grafik

p.s. i didn't plan to PR from this branch so the commit messages are weird, but squash merge to the rescue 🥳 

resolves #252
resolves #243
resolves #176

### CODE REVIEW

**Review by lucasfernog — APPROVED** [review]

**Comment by robertkern** [comment]
Thanks so much for this change. I know it hasn't been tagged so shouldn't be being used at the moment, but i was testing it out with the commit hash as the action version and get the error `assetPath is not defined` which looks like it's coming from https://github.com/tauri-apps/tauri-action/blob/ce22b932cbf2a84235742c1bf7624da3af4e7277/packages/action/src/upload-release-assets.ts#L54 (other references were changed to `asset.path`) just a heads up @FabianLars

**Comment by FabianLars** [comment]
thanks, fixed it.
If it still doesn't work you can try the commit hash of the merge of this PR _before_ the other pr got merged: a99d0bae58a558b23da95394a2a38122574b0f78 (but please report any other issues before that :D )

Edit: it's not fixed because i forgot to rebuild the action. That has to wait for tomorrow unfortunately

**Comment by Layendan** [comment]
I am still receiving the `assetPath is not defined` error
image
Summary of run: https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3381798110

The only reference to assetPath that I can find that would break the action is this line
```js
a.rest.repos.uploadReleaseAsset({headers:r,name:p,data:s().readFileSync(assetPath),owner:o.context.repo.owner,repo:o.context.repo.repo,release_id:t})
```
in `/packages/action/dist/index.js` which I do not know where that comes from.

**Comment by FabianLars** [comment]
The last part of my last message is still the case. I didn't have access to my dev system today so I couldn't rebuild the action yet. Gonna do that first thing in the morning tho.

**Comment by lucasfernog** [comment]
Pushed it @Layendan , thanks for the report and sorry for this issue, it was probably a wrong merge.

**Comment by Layendan** [comment]
No problem and thank you for the help!

**Comment by Layendan** [comment]
So After a few tests, I have found an error.

Trying to create a release.json for multiple platforms fails after the first one.

The workflow successfully creates the release.json file for the first action that completes, but fails on the other actions of the matrix with a `Unexpected token N in JSON at position 0` error.

I am using this https://github.com/tauri-apps/tauri-action#uploading-the-artifacts-to-a-release example to create the release.

Here is my workflow file: https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3401839275/workflow

And here are a list of different workflows showing that the platform that finishes first is the one that succeeds while all the others fail:
 - https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3389322461
 - https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3401831189
 - https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3382179264

**Pull request merged**
