### PR TITLE
feat: add deploy to custom repo

### LINKED ISSUE #298: Feature request: Make owner and repo configurable
Currently the action will only upload assets to a release in the current repo. My use-case is that i'd like to keep the app code in a private repo and use this action to upload assets to a release in a public repo that I configure (so i can have the app source in a private repo and the binaries in a public repo).

https://github.com/tauri-apps/tauri-action/blob/b2d9983822d6a0f20aaca7543a5e2fc314204159/packages/action/src/upload-release-assets.ts#L36-L37

### PR DESCRIPTION
**Pull request by s00d**
Hello, I don't know why you haven't done this yet, but it's very simple and clear.

The changes allow creating a release in a separate repository, requiring the use of 4 parameters: owner, repo, GITHUB_TOKEN, and releaseCommitish.

I added the description to the readme.

### CODE REVIEW

**Review by FabianLars — CHANGES_REQUESTED** [review]
Thanks for contributing!

A few things and then this will be ready to go:
- I think it's fine if you move the context.repo.owner into index.ts when the const is declared instead of falling back to null. Should hopefully make the code even cleaner
- I think the readme changes belongs into the `Release Configuration` block instead.
- Please run `pnpm format` after the changes -> I will add the missing github workflow for that check in the meantime.
- Lastly, we'll also need a changefile, similar to this one https://github.com/tauri-apps/tauri-action/blob/5eb86f2895edc041147c42d25bee9dc899de189b/.changes/artifacts-output.md?plain=1

Thanks again :)

**Comment by s00d** [comment]
@FabianLars done, thanks for the reply

**Comment by s00d** [comment]
@FabianLars done, thanks for the reply

**Review by FabianLars — APPROVED** [review]
Thank you!

**Pull request merged**
