### PR TITLE
Generate updater JSON file

### LINKED ISSUE #251: Option to generate`latest-version.json` for Updater on release
Hi there, thanks for maintaining this!

The [Updater](https://tauri.studio/docs/distribution/updater) can use static JSON files hosted on github to let clients check where to download new versions. This action can create artifacts and host them on github. It seems possible that this action could create the static JSON files that point to these artifacts, too. 

Example output JSON:

```json
{
  "name": "v0.31.1",
  "notes": "My release notes!",
  "pub_date": "2022-04-01T19:25:57Z",
  "platforms": {
    "darwin": {
      "url": "https://github.com/joepio/atomic-data-rust/releases/download/v0.31.1/Atomic.Server_0.31.1_aarch64.m1.macbook.dmg"
    },
    "linux": {
      "url": "https://github.com/joepio/atomic-data-rust/releases/download/v1.0.0/app.AppImage.tar.gz"
    },
    "win64": {
      "url": "https://github.com/joepio/atomic-data-rust/releases/download/v1.0.0/app.x64.msi.zip"
    }
  }
}
```

Example `tauri.conf.json`:

```json
    "updater": {
      "active": true,
      "endpoints": [
        "https://raw.githubusercontent.com/joepio/atomic-data-rust/master/desktop/latest-version.json"
      ],
      "dialog": true
    },
```

Is this already the case, and am I missing something, or is this a nice feature?

Seems pretty doable:

- [ ] Add a flag to the action to enable auto updates. Inform users that this entails creating a commit that updates / adds a file.
- [ ] By default, create a `latest-version.json` in the root directory after creating the artifacts, and link to the download URLs of the artifacts.

### PR DESCRIPTION
**Pull request by mantou132**
See #251

### CODE REVIEW

**Comment by mantou132** [comment]
e.g: https://github.com/mantou132/nesbox/runs/7246181743

**Comment by Janaka-Steph** [comment]
Can we have update on this please?

**Comment by smy20011** [comment]
Is it possible to get it merged? Thank you!

**Comment by Layendan** [comment]
@lucasfernog Would you mind reviewing and merging these changes? A lot of developers, including me, would love to have this as an option.

**Comment by lucasfernog** [comment]
I'll merge this but I'll leave it in the dev branch for a while. To use it in a workflow, you can just change `- uses: tauri-apps/tauri-action@v0` to `- uses: tauri-apps/tauri-action@dev`.

**Comment by Layendan** [comment]
So After a few tests, I have found an error.

Trying to create a release.json for multiple platforms fails after the first one.

The workflow successfully creates the release.json file for the first action that completes, but fails on the other actions of the matrix with a `Unexpected token N in JSON at position 0` error.

I am using this https://github.com/tauri-apps/tauri-action#uploading-the-artifacts-to-a-release example to create the release.

Here is my workflow file: https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3401839275/workflow

And here are a list of different workflows showing that the platform that finishes first is the one that succeeds while all the others fail:
 - https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3389322461
 - https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3401831189
 - https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3382179264
 
 *Sorry for repost, original was in wrong pull/issue*

**Comment by FabianLars** [comment]
@Layendan Can you try the `fix/json-upload` branch please?

**Comment by Layendan** [comment]
I have tested the changes and it appears that it works.
Here is the workflow for it: https://github.com/Layendan/NineAnimator-Tauri/actions/runs/3415169451

Thank you for fixing it and if you don't mind, could you explain what was going wrong, I can't seem to figure it out based on the commits you made.

Is it just using octokit instead of fetch that fixes it?

**Comment by FabianLars** [comment]
> Is it just using octokit instead of fetch that fixes it?

That, and using the rest api instead of browser_download_url (which as its name suggests is really meant for user controlled browsers). It was basically just an authentication issue.

**Pull request merged**
